// Generated by scripts/gen-api-reference.mjs. Do not edit.
import type { DocItem } from './docroutes'

export const referenceItems: DocItem[] = [
  {
    "title": "Overview",
    "href": "/docs/reference"
  },
  {
    "title": "RpcClient",
    "href": "/docs/reference/rpcclient"
  },
  {
    "title": "RpcNetworkError",
    "href": "/docs/reference/rpcnetworkerror"
  },
  {
    "title": "RpcParseError",
    "href": "/docs/reference/rpcparseerror"
  },
  {
    "title": "RpcResponseError",
    "href": "/docs/reference/rpcresponseerror"
  },
  {
    "title": "RpcRouter",
    "href": "/docs/reference/rpcrouter"
  },
  {
    "title": "RpcTimeoutError",
    "href": "/docs/reference/rpctimeouterror"
  },
  {
    "title": "SimulationError",
    "href": "/docs/reference/simulationerror"
  },
  {
    "title": "TransactionSimulator",
    "href": "/docs/reference/transactionsimulator"
  },
  {
    "title": "XdrDecodeError",
    "href": "/docs/reference/xdrdecodeerror"
  },
  {
    "title": "DecodedOperationResult",
    "href": "/docs/reference/decodedoperationresult"
  },
  {
    "title": "DecodedScError",
    "href": "/docs/reference/decodedscerror"
  },
  {
    "title": "DecodedTransactionResult",
    "href": "/docs/reference/decodedtransactionresult"
  },
  {
    "title": "EndpointHealth",
    "href": "/docs/reference/endpointhealth"
  },
  {
    "title": "RawSimulateResponse",
    "href": "/docs/reference/rawsimulateresponse"
  },
  {
    "title": "RestorePreamble",
    "href": "/docs/reference/restorepreamble"
  },
  {
    "title": "RouterConfig",
    "href": "/docs/reference/routerconfig"
  },
  {
    "title": "RouterState",
    "href": "/docs/reference/routerstate"
  },
  {
    "title": "RpcCaller",
    "href": "/docs/reference/rpccaller"
  },
  {
    "title": "RpcClientConfig",
    "href": "/docs/reference/rpcclientconfig"
  },
  {
    "title": "RpcRequest",
    "href": "/docs/reference/rpcrequest"
  },
  {
    "title": "RpcResponse",
    "href": "/docs/reference/rpcresponse"
  },
  {
    "title": "SimulateOptions",
    "href": "/docs/reference/simulateoptions"
  },
  {
    "title": "SimulateTransactionParams",
    "href": "/docs/reference/simulatetransactionparams"
  },
  {
    "title": "SimulationCost",
    "href": "/docs/reference/simulationcost"
  },
  {
    "title": "SimulationResult",
    "href": "/docs/reference/simulationresult"
  },
  {
    "title": "TransactionErrorInput",
    "href": "/docs/reference/transactionerrorinput"
  },
  {
    "title": "decodeScError",
    "href": "/docs/reference/decodescerror"
  },
  {
    "title": "decodeTransactionResult",
    "href": "/docs/reference/decodetransactionresult"
  },
  {
    "title": "explainTransactionError",
    "href": "/docs/reference/explaintransactionerror"
  },
  {
    "title": "EndpointStatus",
    "href": "/docs/reference/endpointstatus"
  },
  {
    "title": "XdrErrorCategory",
    "href": "/docs/reference/xdrerrorcategory"
  }
]
